[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
requires-python = ">=3.13"
name = "yt_age_faker"
version = "0.0.1"

dependencies = [
    "philh_myftp_biz @ git+https://github.com/MineFartS/Server-Package"
]
